### PR TITLE
remind youtube auth

### PR DESCRIPTION
**Pull request by QaldeK**
Save youtube credentials after first authentification

### CODE REVIEW

**Comment by yogeshwaran01** [comment]
Thank you for your contributions

**Comment by Rexadev** [comment]
It saved email password in .json file ? is that safe ?

**Comment by yogeshwaran01** [comment]
It saved in your local just like `.env` and `client_secret.json`

**Comment by Rexadev** [comment]
@yogeshwaran01 please explain more how this update works. I will update the readme

**Comment by yogeshwaran01** [comment]
It just saves the credentials in Json file for first time, Next time when running the script, it loads credentials from that Json file instead of login again in web browser

**Pull request merged**
